---

- name: Install Python packages depend
  apt: pkg="{{ packages }}" state=latest
  vars:
    packages:
    - python-gobject
    - libcairo2-dev
    - gir1.2-gdl-3
    - gir1.2-appindicator3-0.1
  become: true

- name: Install GouYong package
  command: sudo pip3 install GouYong
  #pip:
    #name: GouYong
    #executable: pip3
    #state: present
  #become: true

- name: Copy GouYong startup applications
  copy:
    src: "/usr/share/applications/{{ item }}"
    dest: "{{ ansible_env.HOME }}/.config/autostart/{{ item }}"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
  with_items:
    - GouYong.desktop
