---

#- name: Configure the Remmina PPA
  #apt_repository: repo="ppa:remmina-ppa-team/remmina-next" state=present

- name: Install Remmina
  apt: pkg="{{ packages }}" state=present
  become: true
  vars:
    packages:
    - remmina
    - remmina-plugin-rdp
