---

- name: Pull OpenGrok Image
  docker_image:
    name: opengrok/docker
  become: true

- name: Create OpenGrok container
  docker_container:
    name: OpenGrok
    image: opengrok/docker
    state: started
    ports:
     - "{{ opengrok.server_port }}:8080"
     - "{{ opengrok.ssh_port }}:22"
    volumes:
      - "{{ opengrok.path }}:/src"
  become: true
