---

- name: Ubuntu desktop environment playbook
  hosts: localhost
  roles:
# Common roles
     - { role: hosts}                            # hosts 文件修改
     - { role: locales, become: true }           # 配置语言和时区
     - { role: common, become: true }            # 安装通用软件
     - { role: zsh, become: true }               # zsh
     - { role: fail2ban, become: true }          # 防止暴力破解
# Server roles
     - { role: ssh, become: true }               # ssh
# 语言环境
     - { role: nodejs, become: true }            # nodejs
     - { role: python, become: true }            # python
     - { role: docker, become: true }            # docker
     - { role: java-openjdk, become: true }      # java jdk
# Desktop roles
  # 系统相关
     - { role: desktop, become: true }           # 安装软件,禁用guest账户
     - { role: desktop-cleanup, become: true }   # 删除亚马逊图标等
     - { role: desktop-autostart, become: true } # 添加删除自启动
     - { role: grub-customizer, become: true }   # grub 图形界面
     - { role: ksuperkey, become: true }         # win键可以打开程序
     - { role: nautilus-plugins, become: true }  # 文件管理器增强
     - { role: notify-osd, become: true }        # 通知osd
     - { role: remmina, become: true }           # 远程桌面
     - { role: shutter, become: true }           # 截图工具
     - { role: sysmonitor, become: true }        # 导航栏监控
  # 界面
     - { role: desktop-preferences-unity }       # 界面设置，快捷键设置
     - { role: adapta-theme, become: true }      # 界面主题
     - { role: arc-theme, become: true }         # 界面主题
     - { role: flatabulous, become: true }       # 界面主题
     - { role: ultra-flat-icons, become: true }  # 系统图标
     - { role: albert, become: true }            # dash
  # 开发工具
     - { role: vim, become: true }               # vim
     - { role: atom, become: true }              # atom
     - { role: ripgrep, become: true }           # rg 搜索
     - { role: smartgit, become: true }          # git客户端
     - { role: dbeaver, become: true }           # 数据库工具
     - { role: vagrant, become: true }           # VirtualBox管理工具
     - { role: virtualbox, become: true }        # 虚拟机
  # 通讯
     - { role: thunderbird, become: true }       # 邮件客户端
     - { role: filezilla, become: true }         # ftp
  # 浏览器
     - { role: firefox, become: true }           # 火狐浏览器
  # 多媒体
     - { role: spotify, become: true }           # 音乐客户端
     - { role: gimp, become: true }              # linux版ps
     - { role: clean, become: true }             # 升级并清理系统

     - { role: vim, become: true }               # vim
     - { role: chrome, become: true }            # chrome
     - { role: 32bitlib, become: true }          # 32位兼容库
     - { role: arm, become: true }               # ARM工具链
     - { role: fonts}                            # powerline字体

