---

- name: Install Mailcatcher packages dependencies(简单SMTP服务器)
  apt: name="{{ packages }}" state=latest cache_valid_time={{ aptcachetime }}
  vars:
    packages:
    - libsqlite3-dev
    - g++
  become: true

- name: Install Mailcatcher Gem i18n dependency
  gem: name=i18n state=present user_install=no

- name: Install Mailcatcher Package
  gem: name=mailcatcher state=present user_install=no

- name: Add Mailcatcher service init.d file
  template: src=service.j2 dest=/etc/init.d/mailcatcher owner=root mode=0755

- name: Add Mailcatcher config template
  template: src=config.j2 dest=/etc/default/mailcatcher

- name: "Ensure Mailcatcher is {{ mailcatcher.start | ternary('started','stopped') }}"
  service: name=mailcatcher state={{ mailcatcher.start | ternary('restarted','stopped') }} enabled={{ mailcatcher.service_enabled }}
