---

- name: Configure the Grub Customizer PPA
  apt_repository: repo="ppa:danielrichter2007/grub-customizer" state=present
  become: true

- name: Install Grub Customizer
  apt: pkg=grub-customizer state=present
  become: true
