---

- name: Install Nautilus additional packages
  apt: pkg={{ packages }} state=latest cache_valid_time={{ aptcachetime }}
  become: true
  vars:
    packages:
    - nautilus-compare
    - nautilus-image-converter
    - nautilus-image-manipulator
    - nautilus-wipe

- name: Install Nautilus additional packages for Ubuntu 14.04
  apt: pkg={{ packages }} state=latest cache_valid_time={{ aptcachetime }}
  become: true
  vars:
    packages:
    - nautilus-open-terminal
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '14.04'
