---

- name: Install Python packages
  apt: pkg={{ item }} state=latest
  with_items:
    - python
    - python-dev
    - python-pip
    - python3
    - python3-dev
    - python3-pip
  become: true

- name: Ensure .pip directory exists
  file: path="{{ ansible_env.HOME }}/.pip" state=directory owner="{{ ansible_env.USER }}" group="{{ ansible_env.USER }}"

- name: Change pip source
  template: src=locale.j2 dest="{{ ansible_env.HOME }}/.pip/pip.conf"

- name: pip upgrade
  shell:
    pip3 install --upgrade pip
  become: true

#- name: Uninstall Python pip
  #apt: pkg={{ item }} purge=yes state=absent
  #with_items:
    #- python-pip
    #- python3-pip
  #become: true
