---

- name: Configure the EugeneSan PPA
  apt_repository: repo="ppa:eugenesan/ppa" state=present
  become: true

- name: Install SmartGit
  apt: pkg=smartgit state=latest
  become: true

- name: Create SmartGit desktop file
  copy: src="smartgit.desktop" dest="{{ ansible_env.HOME }}/.local/share/applications/smartgit.desktop" owner="{{ ansible_env.USER }}" group="{{ ansible_env.USER }}"
