---

- name: Install HHVM gpg key(php执行引擎)
  apt_key: url=http://dl.hhvm.com/conf/hhvm.gpg.key state=present

- name: Add HHVM repository
  apt_repository: repo='deb http://dl.hhvm.com/ubuntu {{ ansible_distribution_release }} main' state=present

- name: Install HHVM packages
  apt: pkg={{ packages }} state=latest cache_valid_time={{ aptcachetime }}
  vars:
    packages:
      - hhvm
      - libgmp-dev
      - libmemcached-dev

- name: Configure HHVM user and group
  lineinfile: dest=/etc/default/hhvm regexp="^#?{{ item.param }}=" line='{{ item.param }}="{{ item.value }}"'
  with_items :
    - { param: RUN_AS_USER, value: "{{ hhvm.run_as }}" }
    - { param: RUN_AS_GROUP, value: "{{ hhvm.run_as }}" }

- name: "Ensure HHVM is {{ hhvm.start | ternary('started','stopped') }}"
  service: name=hhvm state={{ hhvm.start | ternary('restarted','stopped') }} enabled={{ hhvm.service_enabled }}
