---

- name: Add apt keys of spotify
  apt_key: keyserver=hkp://keyserver.ubuntu.com id=931FF8E79F0876134EDDBDCCA87FF9DF48BF1C90
  become: true

- name: Add repository
  apt_repository: repo="deb http://repository.spotify.com stable non-free"
  become: true

- name: Install spotify
  apt: name=spotify-client update_cache=yes state=latest
  async: 1800
  become: true
