---

- name: Install 32bit compatible lib
  apt: pkg={{ packages }} state=latest cache_valid_time={{ aptcachetime }}
  vars:
    packages:
    - lib32ncurses5
    - lib32z1
    - libtcl8.5:i386
    - lib32stdc++6
    - libreadline6:i386
    - libexpat1:i386
    - libssl1.0.0:i386
  become: true
  when: ansible_machine == 'x86_64'
