---

- name: Installing apt-key
  apt_key: url=https://dl.google.com/linux/linux_signing_key.pub state=present

- name: Add deb repository
  apt_repository: repo='deb http://dl.google.com/linux/chrome/deb/ stable main' state=present

- name: Install Chrome
  apt:
    name: google-chrome-stable
    state: latest
    update_cache: yes
    cache_valid_time: "{{ aptcachetime }}"
