---

- name: Install Python packages depend
  apt: pkg={{ item }} state=latest
  with_items:
    - python-psutil
    - python3-psutil
  become: true

- name: Install thefuck package
  pip:
    name: thefuck
    executable: pip3
    state: present
  become: true
