---

- name: Install Python packages depend
  apt: pkg={{ packages }} state=latest
  vars:
    packages:
    - python-psutil
    - python3-psutil
  become: true

- name: Install thefuck package
  pip:
    name: thefuck
    executable: pip3
    state: present
  become: true
