---

- name: show package info
  debug:
    msg: "{{ package }}"

- name: Check if {{ package.name }} is installed
  command: dpkg-query -W {{ package.name }}
  register: package_deb_check
  failed_when: package_deb_check.rc > 1
  changed_when: package_deb_check.rc == 1

- name: Install {{ package.url.strip().split('/')[-1] }} package
  apt:
    deb: "{{ package.url }}"
  when: package_deb_check.rc == 1
  become: true

- name: Install {{ package.url.strip().split('/')[-1] }} dependence
  command: apt install -f
  when: package_deb_check.rc == 1
  become: true
