---

- name: Installing apt-key
  apt_key: keyserver=keyserver.ubuntu.com id=331D6DDE7F8840CE
  become: true

- name: Add deb repository
  apt_repository: repo='deb http://www.scootersoftware.com/ bcompare4 non-free' state=present filename=scootersoftware
  become: true

- name: Install bcompare4
  apt:
    name:  bcompare
    state: latest
    update_cache: yes
    cache_valid_time: "{{ aptcachetime }}"
  become: true

#- name: Run deb_install role
  #import_tasks:
    #roles/deb_install/tasks/main.yml
  #vars:
    #package: "{{ package_list[role_name] }}"

