---

- name: Installing apt-key
  apt_key: keyserver=keyserver.ubuntu.com id=331D6DDE7F8840CE
  become: true

- name: Add deb repository
  apt_repository: repo='deb http://www.scootersoftware.com/ bcompare4 non-free' state=present filename=scootersoftware
  become: true

- name: Install bcompare4
  apt:
    name:  bcompare
    state: latest
    update_cache: yes
    cache_valid_time: "{{ aptcachetime }}"
  become: true

#- name: Run deb_install role
  #import_tasks:
    #roles/deb_install/tasks/main.yml

- name: Ensure bcompare config directory exists
  file:
    name: "{{ bcompare.path }}"
    state: directory
  become: true
  when: bcompare.hack

- name: Ensure bcompare config file exists
  file:
    name: "{{ bcompare.path }}/{{ bcompare.config_file }}"
    state: file
  become: true
  when: bcompare.hack

- name: Hack bcompare
  command:
    sed -i "{{ bcompare.key }}" "{{ bcompare.config_file }}"
  args:
    chdir: "{{ bcompare.path }}"
    warn: no
  become: true

- name: Copy key file.
  copy:
    src: "BC4Key.txt"
    dest: "{{ bcompare.path }}/{{ bcompare.key_file }}"
  become: true
