---

- name: Add MaIm repository(maim命令截图)
  apt_repository: repo="ppa:nilarimogard/webupd8" state=present
  become: true

- name: Install MaIm
  apt: name=maim state=latest update_cache=yes cache_valid_time={{ aptcachetime }}
  become: true
