---

- name: Ensure the system can use the HTTPS transport for APT
  stat: path=/usr/lib/apt/methods/https
  register: apt_https_transport
  become: true

- name: Install HTTPS transport for APT
  apt: pkg=apt-transport-https state=installed
  become: true
  when: not apt_https_transport.stat.exists

- name: Enable all repositories in sources.list
  replace: dest=/etc/apt/sources.list regexp='^#\s?deb(.+)http://(.+)/ubuntu(.+)$' replace='deb\1http://\2/ubuntu\3' backup=yes
  become: true

- name: Ensure that Aptitude repositories are up to date
  apt: update_cache=yes cache_valid_time={{ aptcachetime }}
  become: true

- name: Install common packages
  apt: name={{ packages }} state=latest cache_valid_time={{ aptcachetime }}
  async: 1800
  become: true
  vars:
    packages:
    - afuse
    - aptitude
    - axel
    - build-essential
    - bzip2
    - colortest
    - curl
    - diffutils
    - dos2unix
    - fdupes
    - ftp-ssl
    - gawk
    - gcc
    - git
    - grep
    - gzip
    - htop
    - httping
    - iftop
    - imagemagick
    - iotop
    - less
    - lftp
    - make
    - nano
    - nfs-common
    - nmap
    - openssl
    - p7zip-full
    - pv
    - pwgen
    - ranger
    - rar
    - rsync
    - smbclient
    - software-properties-common
    - sshfs
    - sshpass
    - tar
    - tmux
    - trash-cli
    - tig
    - unzip
    - vim
    - wget
    - whois
    - zip
    - bash-completion
    - ncdu
    - screen
    - unrar
    - unzip
    - tcpdump
    - autojump
    - adb
    - tree
    - trash-cli
    - cifs-utils
    - pdftohtml
    - tmux
    - silversearcher-ag

- name: Upgrade installed packages
  apt: upgrade=yes
  async: 1800
  become: true
