---

- name: Show user
  debug:
    msg: "auth {{ ansible_env.USER }}"

#- name: Show password
  #debug:
    #msg: "password >>{{ ansible_become_pass }}<<"

- name: date
  shell:
    date
  register: result

- name: ls
  shell:
    ls
  become: true

- name: Show debug info
  debug:
    var=result

- name: Install common packages
  apt: name={{ packages }} state=latest update_cache=yes cache_valid_time={{ aptcachetime }}
  become: true
  vars:
    packages:
    - afuse
    - aptitude
    - axel
    - build-essential

- name: 软件源更新
  apt:
    update_cache: true
  become: true
