---

- name: Set npm global packages path(js自动构建)
  command: npm config set prefix "{{ ansible_env.HOME }}/.npm-packages"
  changed_when: false

- name: Installs gulp globally using npm
  npm: name=gulp state=present global=yes
