---

- name: Installing apt-key
  apt_key:
    url: "http://mirrors.aliyun.com/docker-ce/linux/ubuntu/gpg"
    state: present
  become: true

- name: Add deb repository
  apt_repository:
    repo: "deb [arch=amd64] http://mirrors.aliyun.com/docker-ce/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
  become: true

- name: Install
  apt:
    pkg: "{{ packages }}"
    state: latest
    cache_valid_time: "{{ aptcachetime }}"
    update_cache: yes
  vars:
    packages:
    - linux-image-extra-virtual
    - docker-ce
    - docker-compose
  become: true

- name: Create Docker group
  group:
    name: docker
    state: present
  become: true

- name: Add current user to Docker group
  user:
    name: "{{ ansible_env.USER }}"
    groups: docker
    append: yes
  become: true

- name: "Ensure Docker is {{ docker.start | ternary('started','stopped') }}"
  service:
    name: docker
    state: "{{ docker.start | ternary('restarted','stopped') }}"
    enabled: "{{ docker.service_enabled }}"
  become: true
