---

- name: Installing apt-key
  apt_key:
    id: "F76221572C52609D"
    url: https://apt.dockerproject.org/gpg
    state: present
  become: true

- name: Add deb repository
  apt_repository:
    repo: 'deb https://apt.dockerproject.org/repo ubuntu-{{ ansible_distribution_release }} main'
    state: present
  become: true

- name: Install
  apt:
    pkg: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - linux-image-extra-virtual
    - docker-engine
    - docker-compose
  become: true

- name: Create Docker group
  group:
    name: docker
    state: present
  become: true

- name: Add current user to Docker group
  user:
    name: "{{ ansible_env.USER }}"
    groups: docker
    append: yes
  become: true

- name: "Ensure Docker is {{ docker.start | ternary('started','stopped') }}"
  service:
    name: docker
    state: "{{ docker.start | ternary('restarted','stopped') }}"
    enabled: "{{ docker.service_enabled }}"
  become: true
