---
# tasks file for vim
- name: remove vim package
  apt: pkg="vim" purge=yes
  with_items:
    - vim

- name: Add vim repository
  apt_repository: repo="ppa:jonathonf/vim" state=present

- name: Install latest vim package
  apt: pkg="vim" state=latest update_cache=yes cache_valid_time={{ aptcachetime }}

