---

- name: Copy common rules to /etc/udev/rules.d/
  copy:
    src: "{{ item }}"
    dest: /etc/udev/rules.d/
  with_fileglob: "*"
  notify:
    - Restart udev services
  become: true

- name: USB ID rules config /etc/udev/rules.d/
  template:
    src: 91-usbid.j2
    dest: /etc/udev/rules.d/91-usbid.rules
  become: true
  notify:
  - Restart udev services

