---

- name: Create host directory
  file: path="{{ ansible_env.HOME }}/tmp/hosts" state=directory
  register: projects_directory_create

- name: Clone hosts repository
  git: repo=https://github.com/googlehosts/hosts.git dest="{{ ansible_env.HOME }}/tmp/hosts" update=yes accept_hostkey=yes depth=1
  when: projects_directory_create.changed

- name: Write hosts file
  blockinfile:
    block: "{{ lookup('file', '{{ ansible_env.HOME }}/tmp/hosts/hosts-files/hosts') }}"
    dest: /etc/hosts
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
  become: true
  notify:
    - Restart networking
