---

- name: Install Memcached(分布式高速内存对象缓存系统)
  apt: pkg=memcached state=latest update_cache=yes cache_valid_time={{ aptcachetime }}

- name: "Ensure Memcached is {{ memcached.start | ternary('started','stopped') }}"
  service: name=memcached state={{ memcached.start | ternary('restarted','stopped') }} enabled={{ memcached.service_enabled }}
