---

- name: Configure the Claws Mail PPA(邮件客户端)
  apt_repository: repo="ppa:claws-mail/ppa" state=present
  become: true

- name: Install Claws Mail
  apt: pkg="{{ packages }}" state=latest
  vars:
    packages:
    - claws-mail
    - claws-mail-i18n
    - claws-mail-extra-plugins
    - claws-mail-plugins
    - claws-mail-multi-notifier
    - claws-mail-themes
  become: true
