- name: VS Code (customization)
  hosts: 127.0.0.1
  connection: local

  tasks:
    - set_fact: is_wsl={{ lookup('file', '/proc/version') is search('microsoft') }}

    - name: Install VS Code Extentions
      command: code --install-extension {{ item }}
      args:
        creates: ~/.vscode/extensions/{{ item }}-*/package.json
      loop:
        - streetsidesoftware.code-spell-checker           # Code Spell Checker
        - editorconfig.editorconfig                       # EditorConfig for VS Code
        - thenikso.github-plus-theme                      # GitHub Plus Theme
        - ms-vsliveshare.vsliveshare-pack                 # Live Share Extension Pack
        - pkief.material-icon-theme                       # Material Icon Theme
        - eamodio.toggle-excluded-files                   # Toggle Excluded Files
        - pflannery.vscode-versionlens                    # Version Lens
        - visualstudioexptteam.vscodeintellicode          # Visual Studio IntelliCode
        - ms-vscode-remote.vscode-remote-extensionpack    # Remote Development
      when: not is_wsl

    - name: Override default VS Code preferences
      copy:
        src: settings.json
        dest: ~/.config/Code/User/settings.json
      when: not is_wsl

    - name: Override default VS Code key bindings
      copy:
        src: keybindings.json
        dest: ~/.config/Code/User/keybindings.json
      when: not is_wsl

    - name: Use VS Code as default editor via GUI, nano via SSH
      blockinfile:
        path: ~/.bashrc
        marker: "### {mark} Ansible managed: Default editor"
        block: |
          if [ -z "$SSH_CONNECTION" ]; then
            export EDITOR='code --wait'
          else
            export EDITOR='nano'
          fi
      when: not is_wsl
