---

- name: Configure the Dockbar PPA(xfce桌面插件)
  apt_repository: repo="ppa:dockbar-main/ppa" state=present
  become: true

# xfce4-panel --quit ; pkill xfconfd ; xfce4-panel &
# xfce4-panel --restart
- name: Install DockbarX XFCE plugin
  apt: pkg={{ packages }} state=latest
  become: true
  vars:
    packages:
    - xfce4-dockbarx-plugin
    - dockbarx-themes-extra
